### PR TITLE
add GitHub Actions CI

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
ready for review.

**Comment by iconara** [comment]
Are you a bot, or is there a particular reason for this PR?

**Comment by sullis** [comment]
> Are you a bot, or is there a particular reason for this PR?

I am not a bot.  I am evaluating this library and I was looking to see if there was a CI build.

I didn't see any GitHub Actions workflows, so I opened this PR.

**Comment by sullis** [comment]
@iconara  is this library still maintained?  I am evaluating the library for an upcoming project.

**Comment by iconara** [comment]
Not actively maintained, no. We've made releases on request a few times the last years, but there is no active development, and I don't work for the company that owns it anymore.

**Comment by sullis** [comment]
@iconara  can somebody merge this PR?  Are you looking for additional contributors on this library?

**Comment by sullis** [comment]
can somebody merge this PR? ( Are you looking for additional contributors on this library? )

**Comment by iconara** [comment]
Hi @sullis, we've discussed this and decided to officially deprecate this project. The two of us that built it initially are no longer in the company that owns it, and the company hasn't used it in years. We will put this repo in archive mode.

You are welcome to fork the repo and create your own package, we only ask that you rename the io.burt package, in addition to adhere to the license (BSD 3-clause, not very restrictive).

**Pull request closed without merging**
