### PR TITLE
added Gson runtime

### PR DESCRIPTION
**Pull request by linehrr**
Changes to be committed:
	new file:   jmespath-gson/pom.xml
	new file:   jmespath-gson/src/main/java/io/burt/jmespath/gson/GsonRuntime.java
	new file:   jmespath-gson/src/test/java/io/burt/jmespath/gson/GsonComplianceTest.java
	new file:   jmespath-gson/src/test/java/io/burt/jmespath/gson/GsonTest.java
	modified:   pom.xml

### CODE REVIEW

**Comment by iconara** [comment]
Thank you for the PR @linehrr. I haven't had time to go through it yet, but it seems like the Travis build is broken, yes. It's probably something that Travis has changed the last year that is acting up, they're not the best keeping things backwards compatible (but hey, it's free so I'm not complaining really). If you can figure it out that would be very helpful.

**Comment by iconara** [comment]
Excellent, thank you. I will try to get some time to look at this more closely. Could you describe a little bit more what it is that you have done, is this just the dump #29 made into a PR, or have you done anything else?

**Comment by linehrr** [comment]
@iconara 
ok all tests passed.
what I have done:
1. added Gson runtime.
2. fixed travis.yml file to upgrade jdk from 1.7 to 1.8.

that's about it, no touch to the core.

**Comment by linehrr** [comment]
@iconara can you please review this PR and hopefully make it into release 0.2.1? 
that way our project can move over to 0.2.1 and don't have to deal with the Gson Jackson conversion headache. thanks !

**Comment by iconara** [comment]
This was released in [jmespath-0.2.1](https://github.com/burtcorp/jmespath-java/releases/tag/jmespath-0.2.1).

@linehrr there is also a [jmespath-0.3.0-SNAPSHOT](https://github.com/burtcorp/jmespath-java/releases/tag/jmespath-0.3.0-SNAPSHOT) which was what I meant to release, but Maven is not my strongest suit. That release includes another improvement, but if you have custom functions you will have to change your code slightly (_very_ slightly). As soon as you tell me that release works for you I will release a non-snapshot version.

Thank you for getting the Gson and for your help getting the Travis config up to date again.

**Comment by linehrr** [comment]
@iconara we don't have any custom UDF. so I think you can go ahead and release it.
since it's `0.3.0`, it's not meant to be backward compatible.
so we should be fine here. (`0.2.1` might be broken since we introduced back-breaking code inside, in theory it should be backward compatible with `0.2.x`)

**Pull request merged**
