### PR TITLE
Compliance fixes

### PR DESCRIPTION
**Pull request by iconara**
#10 fixed a lot of the remaning compliance tests, but there are still 30 left that need to be fixed. This PR aims to fix them all.

### CODE REVIEW

**Comment by iconara** [comment]
Now there are only 5 tests left, and they all have to do with how wildcards are handled.

I'm not too happy about the implementation of the slice operator, it looks really messy, so if someone wants to take a look I'd be grateful.

**Comment by iconara** [comment]
Now there's only two cases left, but I'm struggling with wether or not projection is properly implemented. The spec is not very clear on how projections work, and I can't really wrap my head around the remaning cases.

**Comment by grddev** [comment]
> I'm not too happy about the implementation of the slice operator, it looks really messy, so if someone wants to take a look I'd be grateful.

I took a stab at it and pushed to the branch. Feel free to discard/improve in any way you like. :)

> Now there's only two cases left, but I'm struggling with wether or not projection is properly implemented.

I believe that I understand how the JMESPath specification says it should work, but I don't really understand how the fork/join start-/stop-projection nodes are supposed to work, so I'm not sure I can help with the implementation aspect of things.

The specification says the following for list wildcards (and similarly for hash wildcards) (emphasis mine):

> The [*] syntax (referred to as a list wildcard expression) will return all the elements in a list. Any subsequent expressions will be evaluated _against each individual element_.

I'm not sure that quotation helps you, but it helped me. An alternative way to explain this, would be to rewrite the expression using `map` and `|`. If I'm not mistaken, I think it could be written like this:

    *.<expression>  becomes  * | map(&<expression>, @)
    *.*.foo  becomes  * | map(&* | map (&foo, @), @)

Does that help, or just further confuse things?

**Comment by iconara** [comment]
It's not just `[*]` and `*` that start a projection, the flatten operator and slicing does too (which is not mentioned in the spec). Projections also have to deal with `null` differently from `map`.

The idea of the `StartProjectionNode` thing is to act as more or less a `map` call without the argument type checking and with special `null` handling. I just don't think I've gotten it right, and I've spread the logic around. For some reason I've put the projection handling code in `Node` and not in `StartProjectionNode`. Maybe what I should start with is moving the logic to where it really belongs.

**Comment by iconara** [comment]
The way I've built up the AST is so that the last-most operation is the root of the tree (if you can call it a tree, it doesn't really branch), e.g. `foo.bar | baz` is `Property("baz", Pipe(Property("bar", Property("foo", INPUT))))`. Each operation has a reference to the operation that comes before it in the expression, this is called the "source" operation in the code. This structure is easy to build during parsing.

When the expression is evaluated the last operation is given the input, and it passes that input its source, getting the result back, and then performs its own operation. In other words, each operation only sees the result of all previous operations. Had it not been for projections this would have worked well. Pipe, index, property access, etc. become very natural.

Projections probably work best the other way around, like how the `map` function works, by looping over the elements and passing them one by one to the rest of the expression. At least until you have to deal with a pipe. It's easy to see how `*.foo` can be transformed to `* | map(&:foo, @)`, but `*.foo | bar` should not become `* | map(&(foo | bar), @)`, but `* | map(&foo, @) | bar` – so the AST you build isn't the opposite of what we have now, it's somewhere in between.

Does this make sense?

**Comment by grddev** [comment]
> (if you can call it a tree, it doesn't really branch)

With a stack (or some registers) it seems obvious that you can linearize the AST for evaluation, but that seems like cumbersome format to work with, as pattern matching for optimizations seems like it would be more difficult.

For example, how do you deal with something like `merge(foo.bar, max_by(&boo, baz), qux[1:10])`. At the very least, a linearization would have to decide up front what order to evaluate the arguments, which at the very least makes the original form of the query somewhat difficult to trace.

> `foo.bar | baz` is `Property("baz", Pipe(Property("bar", Property("foo", INPUT))))`

It seems `Pipe` would be more relevant in a ParseTree, and not in an AST? I see that it carries information for the outer `baz` property node to act no the outer node, rather than an internal node (if there had been a projection), but the pipe itself doesn't really do anything, or?

> At least until you have to deal with a pipe. It's easy to see how `*.foo` can be transformed to `* | map(&:foo, @)`, but `*.foo | bar` should not become `* | map(&(foo | bar), @)`, but `* | map(&foo, @) | bar`

I don't see why that example complicates things. As far as I understand, `*.foo | bar` is equivalent to `(*.foo) | bar` (since `.` hash higher precedence). Technically, the grammar is written in such a way that `*.(foo | bar)` is not a legal way to parse the expression, rather than specifying the precedence for `.`.

While you could definitely evaluate the expression from the inside out, but that basically requires a `Property` node for `foo` in `*.*.foo` to know that it is two levels deep, so that it knows to modify the values two levels down in the result returned from `*.*`. Building the tree from left-to-right, seems like it should make evaluation of all 'projections' simpler, while making the other operations about as simple as before, but I might be missing something.

**Comment by iconara** [comment]
There is no `Pipe`, I should have written `StopProjection`, which is the operation that is inserted when a pipe is encountered.

**Comment by iconara** [comment]
Function calls is the only place now, I think, where the AST branches, but I think what I'm taking home from this discussion is that I need to handle projections in the parser/compiler and think of them more like how I handle functions with expression arguments.

In the current implementation the expression `foo.*.*.bar | baz` becomes:

```
Property("baz",
  StopProjection(
    Property("bar",
      StartProjection(
        FlattenObject(
          StartProjection(
            FlattenObject(
              Property("foo"))))))))
```

But this would probably work better:

```
Property("baz",
  Projection(
    Projection(
      Property("bar"),
      FlattenObject()),
    FlattenObject(
      Property("foo"))))
```

Perhaps this doesn't make any sense outside my head, but in essence it means that projections are rewritten so that they take the operations up until the next pipe as an argument, more or less like how a function call with `&` before one of the arguments will take that expression as argument.

It will take some tweaking of the parser/compiler, but it should work.

**Comment by iconara** [comment]
I will finalize this branch and start on a new PR for the projection fixes.

**Comment by grddev** [comment]
I guess I still don't understand what a projection is, even with the tree view. I guess my fundamental problem is that I think it is easier to think of the expression as pushing from left to right, rather than pulling from right to left. Thus, I would have expected the tree from `foo.*.*.bar | baz` to becomes something along the lines of:

    Sequence(
      Property("foo"),
      ObjectWildcard(ObjectWildcard(Property("bar"))),
      Property("baz"))

Technically, I guess it could be two sequencing operations, (one for the the first `.` and one for the `|`), but main point here is that the evaluation structure is made clear. Specifically, the object structure reflects that the second `ObjectWildcard` is evaluated in the context of the first `ObjectWildcard`.

**Comment by iconara** [comment]
The reason for the projection node/operation in my examples is to separate the projection operation from the operation that starts a projection. There are multiple operations that start projections, array wildcard, object wildcard, flatten array, slice, and filter (I think those are all), and besides array wildcard they do something that doesn't have anything to do with projection. Slice extracts a portion of an array and then the expression up until the next pipe is executed on each element in the slice (i.e. is projected on the slice); flatten flattens an array and then the rest of the expression up until the next pipe is executed on each element in the flattened array; etc. There are two operations and therefore I think having two operations in the AST makes it easier to reason about it.

In contrast `ObjectWildcard(ObjectWildcard(Property("bar")))` hides the projection. Implementation-wise you could of course make `ObjectWildcard` subclass a `Projection` base class to handle it, but at least when talking about it I think it helps to separate the two operations.

**Comment by grddev** [comment]
You said it before, but it didn't really sink in before. I just didn't think of `Projection` as such an important abstraction, as it is essentially just a map followed by a null-filter. But sure, `ObjectWildcard(x)` could be replaced by `Projection(ObjectWildcard(),x)` in my example to separate the generator from the map-filter.

With that in mind, I think I understand at least the tree view, the expression `Projection(x, y)` means pull values from `y` and feed them into `x`, building up the projected result while we go. I still struggle a bit to understand how the "input" is fed into the tree, but I guess all the leaves of the tree pull from the input, but while running in a projection, the "current input" would have to be replaced by the somehow, so that the `FlattenObject()` pulls values generated by the outer `Projection`, rather than from the user input.

In my mind it seems more straightforward to push the input into the root, and let each node decide what values the nodes below it would operate on, but I guess that would be a nontrivial change (and there might be other downsides to doing it like that).

**Comment by iconara** [comment]
It would be nontrivial to change the direction of the tree, and I also think it's easier to build the expression tree in the parser this way, but I might be wrong.

I think it wouldn't be a problem to get projections working properly if I just manage to build the tree structure I have in my head. What I'm struggling with now is trying to build that tree.

**Pull request merged**
